language: ruby
rvm:
- 2.6
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - master
script:
  - JEKYLL_ENV=production bundle exec jekyll build
deploy:
  provider: pages:git
  local-dir: ./_site
  email: deploy@travis-ci.org
  name: Deployment Bot
  token: $GITHUB_TOKEN
  keep-history: true
  edge: true
  on:
    branch: master
