language: ruby
rvm:
- 2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - master
script:
  - bundle exec jekyll build
  - bundle exec rake test
deploy:
  provider: pages
  local-dir: ./_site
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master