# Build settings
markdown: redcarpet
highlighter: pygments
paginate: 5
language: 'fa-IR'
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jalalidate
  - jemoji

# Site settings
title: "بهروزم"
description: > # manga / anime / gnu linux / networking
email: b.hasanbg[at]gmail[dot]com
#blog logo
logo: "/assets/images/logo2.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'behroozam'
author: 'behrooz hasanbeygi'
author_image: "/assets/images/behroozam.jpg"


url: "http://behroozam.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/b3hroozam
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/behroozam
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	instagram
    url:	https://instagram.com/behroozam
    desc:	Follow me
    share_url:
    share_title:
    share_link:
