title: بهروزم # name of the site
author: Behrouz Hasanbeygi # name of site's author
email: riccardo.graziosi97@gmail.com # email of site's author
url: https://behroozam.com # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  بهروزم جایی که یاد گرفتم بهبود یه تلاش دائمی است

permalink: /:slug.html

favicon: "favicon.ico" # name+extension of favicon (which must be put on the root folder)

google_analytics: "UA-37514057-2"

future: true # if the post is belong to the future :))

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: bash
    css_class   : 'syntax'

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%F %R" # customize how date is formatted
  jdate_format: "%A %d %b %Y" # jalali date format
  show_description: false # show blog description in home page

sass:
  style: :compressed

comments: true

collections:
  - medium_posts

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-jalali
  - jekyll-sitemap
  - jekyll-display-medium-posts
  - jekyll-toc

toc:
 min_level: 1
 max_level: 5
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist
