source 'https://rubygems.org'
gem "github-pages"
gem "execjs"
gem 'jekyll-coffeescript'
gem 'jemoji'
gem 'jalalidate'
gem 'therubyracer'
gem 'redcarpet'
gem 'jekyll-paginate'
gem 'kramdown'
gem 'pygments.rb'
gem 'jekyll-jalali'
gem 'jekyll-hinduarabic'
